#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
REPO_NAME="music-discovery"
REPO_DESC="Open-source album catalog and explainable discovery site. Pre-code: the Wayfinder map lives in Issues."

# Run from the repo root, whatever directory the shell started in.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# gh was installed by winget to Program Files; a shell opened before that
# install won't have it on PATH yet.
if ! command -v gh >/dev/null 2>&1 && [[ -x "/c/Program Files/GitHub CLI/gh.exe" ]]; then
  export PATH="/c/Program Files/GitHub CLI:$PATH"
fi
if ! command -v gh >/dev/null 2>&1; then
  printf '%sgh (GitHub CLI) is not on PATH. Install it, then re-run:%s\n' "$RED" "$RESET"
  printf '  winget install --id GitHub.cli --exact\n'
  exit 1
fi

banner "GitHub setup for $REPO_NAME"

# ── 1. account ────────────────────────────────────────────────────────────
stage "GitHub account"
say "Everything else needs a GitHub account. If you already have one, skip ahead."
if ! confirm "Do you already have a GitHub account?"; then
  open_url "https://github.com/signup"
  step "Sign up with your email. Pick a username you're happy to see on a public project;"
  step "it becomes part of the repo URL (github.com/<username>/$REPO_NAME)."
  step "Verify the email when GitHub asks. The free plan is all this project needs."
  pause "Press Enter once you're signed in to GitHub in your browser."
fi

# ── 2. sign gh in ─────────────────────────────────────────────────────────
stage "Sign the gh command-line tool in"
if gh auth status >/dev/null 2>&1; then
  note "gh is already signed in as $(gh api user --jq .login)."
else
  say "gh will show you a one-time code and open github.com/login/device."
  step "Copy the code from this window, paste it into the browser, click Authorize."
  step "If gh asks 'Authenticate Git with your GitHub credentials?', answer Y."
  pause "Press Enter to start."
  gh auth login --hostname github.com --git-protocol https --web
fi
gh auth setup-git >/dev/null 2>&1 || warn "gh auth setup-git failed; git push may prompt for a password"
GH_LOGIN=$(gh api user --jq .login)
printf '  %s✓ signed in%s as %s\n' "$GREEN" "$RESET" "$GH_LOGIN"
pause

# ── 3. create the repo and push ───────────────────────────────────────────
stage "Create the public repo and push master"
if git remote get-url origin >/dev/null 2>&1; then
  note "remote 'origin' already exists: $(git remote get-url origin)"
  git push -u origin master
else
  if [[ -n "$(git status --porcelain)" ]]; then
    warn "working tree has uncommitted changes; they won't be pushed. Commit first if you meant to."
    confirm "Push anyway?" || exit 1
  fi
  say "This creates github.com/$GH_LOGIN/$REPO_NAME as a PUBLIC repo (AGPL-3.0, LICENSE is"
  say "already in the tree) and pushes the local master branch to it. Public is permanent"
  say "in spirit: anyone can clone it from the moment it exists."
  confirm "Create the public repo and push?" || exit 1
  gh repo create "$REPO_NAME" --public --source=. --remote=origin --push --description "$REPO_DESC"
fi
REPO_URL="https://github.com/$GH_LOGIN/$REPO_NAME"
open_url "$REPO_URL"
step "Check the page: the file list should show CONTEXT.md, AGENTS.md, LICENSE, wayfinder/, docs/."
step "Click into wayfinder/ and confirm map.md renders."
pause "Looks right? Press Enter."

# ── 4. issues + labels ────────────────────────────────────────────────────
stage "Enable Issues and create the wayfinder labels"
gh repo edit "$GH_LOGIN/$REPO_NAME" --enable-issues >/dev/null
for pair in "wayfinder:map:5319E7" "wayfinder:research:0E8A16" "wayfinder:prototype:FBCA04" \
            "wayfinder:grilling:D93F0B" "wayfinder:task:1D76DB"; do
  name="${pair%:*}"; color="${pair##*:}"
  gh label create "$name" --color "$color" --force --repo "$GH_LOGIN/$REPO_NAME" >/dev/null
  printf '  %s✓ label%s %s\n' "$GREEN" "$RESET" "$name"
done
pause

# ── 5. migrate the tracker ────────────────────────────────────────────────
stage "Move the Wayfinder map and tickets into Issues"
say "scripts/migrate-tracker.py creates one issue per ticket (#1–#19, same numbers as"
say "the files), then the map issue (#20), wires sub-issues and 'blocked by', closes the"
say "six resolved tickets with their resolutions as comments, and rewrites the local"
say "wayfinder/ files to point at GitHub. It refuses to run if the repo already has issues."
confirm "Run the migration?" || exit 1
python scripts/migrate-tracker.py
pause

# ── 6. commit the local changes ───────────────────────────────────────────
stage "Commit and push the tracker move"
git add -A
git status --short
say "Above is what changes locally: map.md becomes a pointer, tickets/ is removed,"
say "TRACKER.md and AGENTS.md describe the GitHub workflow."
confirm "Commit and push to master?" || { warn "left uncommitted; review with git status"; exit 1; }
git commit -q -m "Move the Wayfinder tracker to GitHub Issues (ticket 001)

Map is a wayfinder:map issue; tickets are its sub-issues with native
blocked-by relationships. Local ticket files removed; TRACKER.md and
AGENTS.md updated for the gh workflow.

Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>"
git push
open_url "$REPO_URL/issues"
step "The Issues tab should list 20 issues: the map plus 19 tickets, 6 of them closed."
step "Open the map issue; its sub-issue list is the whole tracker at a glance."
pause "Press Enter to finish."

finish
note "Repo: $REPO_URL"
note "Next session: /wayfinder with the map issue number, and it picks the frontier."
