// PROTOTYPE data — throwaway. Favourites (Sam's own picks) + a hand-assembled
// Candidate pool spanning hip-hop/R&B/alt-rock (matching the shape of Sam's
// Favourites) plus a broader spread (electronic, folk, pop) as a sanity check
// that unrelated genres score low.

export const favourites = [
  { title: "Alfredo", artist: "Freddie Gibbs" },
  { title: "Reasonable Drought", artist: "Stove God Cooks" },
  { title: "In Rainbows", artist: "Radiohead" },
  { title: "Care For Me", artist: "Saba" },
  { title: "In My Lifetime, Vol. 1", artist: "JAY-Z" },
  { title: "X&Y", artist: "Coldplay" },
  { title: "Beat Konducta Vol. 1-2: Movie Scenes", artist: "Madlib" },
  { title: "Please Excuse Me for Being Antisocial", artist: "Roddy Ricch" },
  { title: "Off the Wall", artist: "Michael Jackson" },
];

export const candidates = [
  // Underground / backpack / Griselda-adjacent rap
  { title: "Piñata", artist: "Freddie Gibbs" },
  { title: "Bandana", artist: "Freddie Gibbs" },
  { title: "$oul $old $eparately", artist: "Freddie Gibbs" },
  { title: "Marcberg", artist: "Roc Marciano" },
  { title: "Reloaded", artist: "Roc Marciano" },
  { title: "Griselda Ergo Base", artist: "Griselda" },
  { title: "Kiss the Ring", artist: "Westside Gunn" },
  { title: "Flygod", artist: "Westside Gunn" },
  { title: "God Fermented in Hell", artist: "Mach-Hommy" },
  { title: "Pray for Haiti", artist: "Mach-Hommy" },
  { title: "Look What I Became", artist: "Conway the Machine" },
  { title: "The Plugs I Met", artist: "Benny the Butcher" },
  { title: "This Thing of Ours", artist: "Benny the Butcher" },
  { title: "Fetti", artist: "Curren$y" },
  { title: "Pilot Talk", artist: "Curren$y" },

  // Classic / canonical hip-hop
  { title: "Illmatic", artist: "Nas" },
  { title: "Madvillainy", artist: "Madvillain" },
  { title: "To Pimp a Butterfly", artist: "Kendrick Lamar" },
  { title: "good kid, m.A.A.d city", artist: "Kendrick Lamar" },
  { title: "DAMN.", artist: "Kendrick Lamar" },
  { title: "Aquemini", artist: "OutKast" },
  { title: "Stankonia", artist: "OutKast" },
  { title: "The Blueprint", artist: "JAY-Z" },
  { title: "Reasonable Doubt", artist: "JAY-Z" },
  { title: "The College Dropout", artist: "Kanye West" },
  { title: "My Beautiful Dark Twisted Fantasy", artist: "Kanye West" },
  { title: "Get Rich or Die Tryin'", artist: "50 Cent" },
  { title: "Donuts", artist: "J Dilla" },
  { title: "Since I Left You", artist: "The Avalanches" },
  { title: "Atrocity Exhibition", artist: "Danny Brown" },
  { title: "Long.Live.A$AP", artist: "A$AP Rocky" },
  { title: "Because the Internet", artist: "Childish Gambino" },
  { title: "Some Rap Songs", artist: "Earl Sweatshirt" },
  { title: "I Don't Like Shit, I Don't Go Outside", artist: "Earl Sweatshirt" },
  { title: "Testing", artist: "A$AP Rocky" },

  // Trap / mainstream contemporary hip-hop
  { title: "Astroworld", artist: "Travis Scott" },
  { title: "Whole Lotta Red", artist: "Playboi Carti" },
  { title: "So Much Fun", artist: "Young Thug" },
  { title: "Punk", artist: "Young Thug" },
  { title: "My Turn", artist: "Lil Baby" },
  { title: "Savage Mode", artist: "21 Savage" },
  { title: "i am > i was", artist: "21 Savage" },
  { title: "DS4Ever", artist: "Gunna" },
  { title: "Utopia", artist: "Travis Scott" },
  { title: "Death Race for Love", artist: "Juice WRLD" },

  // Instrumental hip-hop / beat scene
  { title: "Cosmogramma", artist: "Flying Lotus" },
  { title: "Los Angeles", artist: "Flying Lotus" },
  { title: "You're Dead!", artist: "Flying Lotus" },
  { title: "Endtroducing.....", artist: "DJ Shadow" },
  { title: "Modal Soul", artist: "Nujabes" },
  { title: "Metaphorical Music", artist: "Nujabes" },
  { title: "Madlib Medicine Show No. 1", artist: "Madlib" },
  { title: "Shades of Blue", artist: "Madlib" },
  { title: "Rock On", artist: "Knxwledge" },

  // Alt-R&B / neo-soul
  { title: "channel ORANGE", artist: "Frank Ocean" },
  { title: "Blonde", artist: "Frank Ocean" },
  { title: "Ctrl", artist: "SZA" },
  { title: "Voodoo", artist: "D'Angelo" },
  { title: "Black Messiah", artist: "D'Angelo and the Vanguard" },
  { title: "Baduizm", artist: "Erykah Badu" },
  { title: "Mama's Gun", artist: "Erykah Badu" },
  { title: "A Seat at the Table", artist: "Solange" },
  { title: "House of Balloons", artist: "The Weeknd" },
  { title: "Kaleidoscope Dream", artist: "Miguel" },
  { title: "Freudian", artist: "Daniel Caesar" },
  { title: "H.E.R.", artist: "H.E.R." },
  { title: "Igor", artist: "Tyler, the Creator" },
  { title: "Flower Boy", artist: "Tyler, the Creator" },

  // Soul / funk / disco (Off the Wall's neighbourhood)
  { title: "Thriller", artist: "Michael Jackson" },
  { title: "Bad", artist: "Michael Jackson" },
  { title: "Songs in the Key of Life", artist: "Stevie Wonder" },
  { title: "Innervisions", artist: "Stevie Wonder" },
  { title: "Talking Book", artist: "Stevie Wonder" },
  { title: "What's Going On", artist: "Marvin Gaye" },
  { title: "Purple Rain", artist: "Prince and the Revolution" },
  { title: "Sign o' the Times", artist: "Prince" },
  { title: "1999", artist: "Prince" },
  { title: "That's the Way of the World", artist: "Earth, Wind & Fire" },
  { title: "Super Fly", artist: "Curtis Mayfield" },
  { title: "Faith", artist: "George Michael" },
  { title: "Whitney Houston", artist: "Whitney Houston" },

  // Alt-rock / experimental rock (In Rainbows' neighbourhood)
  { title: "OK Computer", artist: "Radiohead" },
  { title: "Kid A", artist: "Radiohead" },
  { title: "Amnesiac", artist: "Radiohead" },
  { title: "The Bends", artist: "Radiohead" },
  { title: "A Moon Shaped Pool", artist: "Radiohead" },
  { title: "Yankee Hotel Foxtrot", artist: "Wilco" },
  { title: "Ga Ga Ga Ga Ga", artist: "Spoon" },
  { title: "The Moon & Antarctica", artist: "Modest Mouse" },
  { title: "Funeral", artist: "Arcade Fire" },
  { title: "The Suburbs", artist: "Arcade Fire" },
  { title: "You Forgot It in People", artist: "Broken Social Scene" },
  { title: "Illinois", artist: "Sufjan Stevens" },
  { title: "For Emma, Forever Ago", artist: "Bon Iver" },
  { title: "Bon Iver, Bon Iver", artist: "Bon Iver" },
  { title: "Dear Science", artist: "TV on the Radio" },
  { title: "Microcastle", artist: "Deerhunter" },
  { title: "Veckatimest", artist: "Grizzly Bear" },
  { title: "Dummy", artist: "Portishead" },
  { title: "Mezzanine", artist: "Massive Attack" },
  { title: "Loveless", artist: "My Bloody Valentine" },
  { title: "Doolittle", artist: "Pixies" },
  { title: "Automatic for the People", artist: "R.E.M." },
  { title: "Remain in Light", artist: "Talking Heads" },
  { title: "Sound of Silver", artist: "LCD Soundsystem" },
  { title: "This Is Happening", artist: "LCD Soundsystem" },
  { title: "Modern Vampires of the City", artist: "Vampire Weekend" },
  { title: "Vampire Weekend", artist: "Vampire Weekend" },
  { title: "Trouble Will Find Me", artist: "The National" },
  { title: "Boxer", artist: "The National" },
  { title: "Turn On the Bright Lights", artist: "Interpol" },
  { title: "Currents", artist: "Tame Impala" },
  { title: "Lonerism", artist: "Tame Impala" },
  { title: "An Awesome Wave", artist: "Alt-J" },

  // Coldplay-adjacent pop-rock
  { title: "A Rush of Blood to the Head", artist: "Coldplay" },
  { title: "Parachutes", artist: "Coldplay" },
  { title: "Viva la Vida or Death and All His Friends", artist: "Coldplay" },
  { title: "Absolution", artist: "Muse" },
  { title: "Black Holes and Revelations", artist: "Muse" },
  { title: "Eyes Open", artist: "Snow Patrol" },
  { title: "Hopes and Fears", artist: "Keane" },
  { title: "All That You Can't Leave Behind", artist: "U2" },
  { title: "The Man Who", artist: "Travis" },

  // Jazz-adjacent / fusion
  { title: "The Epic", artist: "Kamasi Washington" },
  { title: "Black Radio", artist: "Robert Glasper Experiment" },
  { title: "In a Silent Way", artist: "Miles Davis" },
  { title: "Head Hunters", artist: "Herbie Hancock" },

  // Broader spread — sanity-check that unrelated genres score low
  { title: "Discovery", artist: "Daft Punk" },
  { title: "Random Access Memories", artist: "Daft Punk" },
  { title: "Selected Ambient Works 85-92", artist: "Aphex Twin" },
  { title: "Homework", artist: "Daft Punk" },
  { title: "Golden Hour", artist: "Kacey Musgraves" },
  { title: "Fleet Foxes", artist: "Fleet Foxes" },
  { title: "Helplessness Blues", artist: "Fleet Foxes" },
  { title: "1989", artist: "Taylor Swift" },
  { title: "folklore", artist: "Taylor Swift" },
  { title: "How I'm Feeling Now", artist: "Charli XCX" },
  { title: "Melodrama", artist: "Lorde" },
  { title: "Norman Fucking Rockwell!", artist: "Lana Del Rey" },
  { title: "Ummagumma", artist: "Pink Floyd" },
  { title: "The Dark Side of the Moon", artist: "Pink Floyd" },
  { title: "Led Zeppelin IV", artist: "Led Zeppelin" },
  { title: "Rumours", artist: "Fleetwood Mac" },
  { title: "Nevermind", artist: "Nirvana" },
  { title: "In Utero", artist: "Nirvana" },
];
